--  Configuration for elogs generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Elogs_Config is
   pragma Pure;

   Crate_Version : constant String := "1.0.0";
   Crate_Name : constant String := "elogs";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   Max_Log_Count_First : constant := -9223372036854775808;
   Max_Log_Count_Last : constant :=  9223372036854775807;
   Max_Log_Count : constant :=  50;

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

   Version_Length_First : constant := -9223372036854775808;
   Version_Length_Last : constant :=  9223372036854775807;
   Version_Length : constant :=  8;

   Device_ID_Length_First : constant := -9223372036854775808;
   Device_ID_Length_Last : constant :=  9223372036854775807;
   Device_ID_Length : constant :=  12;

   Max_Message_Length_First : constant := -9223372036854775808;
   Max_Message_Length_Last : constant :=  9223372036854775807;
   Max_Message_Length : constant :=  200;

end Elogs_Config;
